services:
  - type: web
    name: competition-platform-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    nodeVersion: 18.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000 